### ISSUE TITLE
Feature Request: Glyphs for Additional Systems.

### ISSUE THREAD

**Issue by clort81** [9999years/Unicode-PETSCII#1]
There are more classic computer glyphs that deserve inclusion!
 http://pelulamu.net/unscii/

**Comment by 9999years** [comment]
I agree! This repo was actually only a small (I think unused...?) part of the (Proposal to add characters from legacy computers and teletext to the UCS)[https://www.unicode.org/L2/L2019/19025-terminals-prop.pdf], which has been accepted to be included in a future version of Unicode.

The Unscii font includes:
- [x] PETSCII characters from the Commodore computers
- [x] Teletext and Videotex are included in the proposal; missing are separate 2x3 grids in the separated forms, specifically, but the solid 2x3 pseudopixel grids *are* included. I *believe* that the separated forms were activated with a control code, and no additional control codes will be added to Unicode -- it's considered platform-specific behavior to identify and interpret control codes.
- [x] Amstrad CPC: the diagonal line junctions and shadings are included, but the Unscii designer also added many other 'inspired' glyphs that did not, historically, exist, and are not in the proposal.
- [ ] Apple Sabine10: Not included / mentioned in the proposal
- [x] VT100 horizontal/vertical lines are included
- [x] Mattel Aquarius: some characters were proposed, but some could not be identified and were not proposed (asking to include some characters you can't identify or find use of in Unicode is pretty much a non-starter):
  > Several of the glyphs in this collection were not identified in earlier revisions of this proposal, and hence are not proposed here. They may be included in a subsequent proposal document. See Section 8 for more information on non-proposed characters.
  However, the Unscii page mentions "rounded corner blocks", which, as far as I can tell, were not part of the Mattel Aquarius character set?
- [ ] Sharp MZ: Not included -- lots of debate about identifying characters, etc. Ultimately, they were just left out.

So, except for two systems (the Apple Sabine10 and the Sharp MZ), all the characters from Unscii are on their way into Unicode!

**Comment by 9999years** [comment]
Closing this because I don't really work on this repo, but I'm happy to discuss and/or ask about adding you to the terminals working group's mailing list if you want to help with the proposals.
